package com.example.applog.movielist.Services

import com.example.applog.movielist.Models.Movie

class MovieApiService {

    fun getActionMovies(): ArrayList<Movie> {
        val movies: ArrayList<Movie> = ArrayList()

        val movie1: Movie = Movie("Mr & Ms Smith","120 mn","Doug Liman","Action","2005","Quand le film commence John (Brad Pitt), directeur de construction, et Jane Smith (Angelina Jolie), consultante en soutien technique répondent à des questions devant un conseiller conjugal. Le couple est marié depuis « cinq ou six ans », mais leur mariage en est au point qu'ils ne se souviennent même plus de la dernière fois où ils ont eu des rapports sexuels. Ils racontent l'histoire de leur première rencontre : c’était à Bogota, en Colombie, après un récent cambriolage tous deux fuyaient secrètement les autorités du pays, à la recherche de touristes qui voyageaient seuls, prétendu être ensemble pour éviter d’être interrogés. Rapidement ils sont tombés amoureux et se sont mariés. John déclare plus tard que Jane était pour lui comme « un matin de Noël » le jour de leur rencontre.","https://image.tmdb.org/t/p/w600_and_h900_bestv2/8dbcRqWSlOUCmrOVTsHfVsOrlFB.jpg")
        val movie2: Movie = Movie("Mission impossible","110 mn","Brian De Palma","Action","1996","TOM CRUISE crève l’écran dans ce film à grand succès, qui «vous cloue à votre siège avant de vous en faire bondir» (Howard Rosenberg, Los Angeles Times). Il incarne Ethan Hunt, un agent secret, accusé de la mort des membres de son équipe. Fuyant le gouvernement responsable de ces assassinats, forçant la sécurité du quartier général de la CIA pour s’y introduire, cramponné au toit d’un TGV, Hunt nous entraîne dans une course-poursuite infernale afin de devancer ses poursuivants et découvrir l’incroyable vérité. Alors votre mission si vous l’acceptez : «être prêt pour l’aventure la plus extraordinaire que vous ayez jamais vue» (Stephen Holden, The New York Times).","http://fr.web.img5.acsta.net/pictures/18/05/14/16/32/0850449.jpg")
        val movie3: Movie = Movie("Kingsman","141 mn","Matthew Vaughn","Action","2017","Kingsman, l’élite du renseignement britannique en costume trois pièces, fait face à une menace sans précédent. Alors qu’une bombe s’abat et détruit leur quartier général, les agents font la découverte d’une puissante organisation alliée nommée Statesman, fondée il y a bien longtemps aux Etats-Unis. Face à cet ultime danger, les deux services d’élite devront unir leurs forces pour sauver le monde.","https://www.foxmovies.com/s3/dev-temp/en-US/__5a00f55221b82.jpg")
        val movie4: Movie = Movie("Fast & Furious","106 mn","Justin Lin","Action","2009","Un crime ramène Don Toretto (Vin Diesel), ex-taulard en cavale à Los Angeles où sa rivalité avec l'agent Brian O'Conner (Paul Walker) refait surface. Forcés de faire face à un ennemi commun, c'est derrière le volant, repoussant les limites de leurs bolides, qu'ils vont pouvoir se venger. Tuning, voitures importées et grosses cylindrées, des rues de Los Angeles jusqu'au désert du Mexique, Paul Walker et Vin Diesel retrouvent Michelle Rodriguez et Jordana Brewster dans un nouvel opus riche en adrénaline!","https://images-na.ssl-images-amazon.com/images/I/71qtDoM-rcL._SY445_.jpg")
        val movie5: Movie = Movie("Matrix","136 minutes","Les Wachowski","Action","1999","Thomas A. Anderson (Keanu Reeves), un jeune informaticien connu dans le monde du hacking sous le pseudonyme de Neo16, est contacté via son ordinateur par ce qu’il pense être un groupe de hackers. Ils lui font découvrir que le monde dans lequel il vit n’est qu’un monde virtuel dans lequel les êtres humains sont gardés inconsciemment sous contrôle.\n" +
                "\n" +
                "Morpheus (Laurence Fishburne), le capitaine du Nebuchadnezzar, contacte Néo et pense que celui-ci est l’Élu qui peut libérer les êtres humains du joug des machines et prendre le contrôle de la matrice (selon ses croyances et ses convictions).","https://images-na.ssl-images-amazon.com/images/I/51vpnbwFHrL._SY445_.jpg")
        val movie6: Movie = Movie("300","111 mn","Zack Snyder","Action","2007","300 retrace la bataille antique des Thermopyles au cours de laquelle le Roi Léonidas et ses 300 Spartiates se sont battus jusqu'à la mort contre Xerxès et son immense armée Perse…","http://fr.web.img3.acsta.net/medias/nmedia/18/36/26/41/18737112.jpg")
        val movie7: Movie = Movie("Gladiateur","117 mn","Ridley Scott","Action","2000","Lauréat de cinq Oscars®, dont ceux du meilleur film et du meilleur acteur, Gladiator est une combinaison éblouissante d’action et de fiction. Découvrez la puissance unique de Gladiator, dirigé d’une main de maître par Ridley Scott et avec la performance fascinante de Russell Crowe.","https://images-na.ssl-images-amazon.com/images/I/71w3h7llKuL._SY445_.jpg")
        val movie8: Movie = Movie("Rocky","101 mn","Sylvester Stallone","Action","2006","Rocky Balboa, l’ex-champion du monde de boxe dans la cinquantaine n’a que son restaurant et ses histoire à raconter. La mort de son épouse lui pèse et son fils ne vient jamais le voir. Les promoteurs du actuel champion, Mason Dixon, lui cherchent désespérément un adversaire à sa taille. Rocky accepte de livrer un combat très médiatisé avec le champion car pour lui c'est l'occasion de revivre et ranimer les braises d'une passion qui ne l'a jamais quitté. ","https://p1.storage.canalblog.com/20/62/1349409/111949275.jpg")
        val movie9: Movie = Movie("Arme fatal","110 mn","Richard Donner","Action","1987","Los Angeles. Policier à la brigade criminelle, Roger Murtaugh, venant de fêter ses cinquante ans, mène une vie paisible auprès de sa femme Trish et de ses trois enfants. Un jour, il apprend par sa femme qu'un vieil ami, Michael Hunsaker, avec qui il a combattu au Viêt Nam, essaie de le contacter. Peu de temps après, il est appelé sur les lieux d'un suicide et découvre que la jeune femme qui s'est défenestrée, Amanda, n'est autre que la fille d'Hunsaker.","http://www.lerepairedesmotards.com/img/dossiers/films/arme-fatale-3_hd.jpg")
        val movie10: Movie = Movie("Terminator","107 mn","James Cameron","Action","1984","En 2029, les machines dominent la planète et tentent d’exterminer la race humaine. Pour anéantir l’avenir de l’homme, elles décident de modifier le passé en envoyant un cyborg indestructible, le Terminator (Arnold SCHWARZENEGGAR), dans un voyage dans le temps. Sa mission : tuer Sarah Connor (Linda HAMILTON), la femme dont l’enfant à venir deviendra le seul espoir de l’espèce humaine. ","http://fr.web.img4.acsta.net/pictures/15/06/29/10/53/495349.jpg")

        movies.add(movie1)
        movies.add(movie2)
        movies.add(movie3)
        movies.add(movie4)
        movies.add(movie5)
        movies.add(movie6)
        movies.add(movie7)
        movies.add(movie8)
        movies.add(movie9)
        movies.add(movie10)

        return movies
    }

    fun getAdventureMovies(): ArrayList<Movie> {
        val movies: ArrayList<Movie> = ArrayList()

        val movie1: Movie = Movie("Tomb Raider","118 mn","Roar Uthaug","Adventure","2017","Lara Croft est la fille très indépendante d'un père excentrique qu'elle a perdu alors qu'elle n'était qu'une adolescente. À maintenant 21 ans, Lara a du mal à trouver sa place dans le monde. Elle est déterminée à tracer sa propre voie plutôt que de prendre les rênes de la multinationale de son père... Alors elle-même ne comprend pas ce qui la pousse à résoudre l'énigme de sa mort mystérieuse. Lara va à l'encontre des dernières volontés de son père et quitte les rues familières de Londres à la recherche d'une île légendaire au large de Hong Kong qui n'existe peut-être pas. Alors que sa vie est menacée à chaque étape et qu'elle n'a aucun entraînement et aucune expérience sur lesquels se reposer, l'esprit aiguisé, la foi aveugle et la ténacité inhérente de Lara sont ses seules armes pour faire face à cette aventure effrénée dans l'inconnu, un baptême du feu chargé en action.","http://fr.web.img6.acsta.net/pictures/18/02/23/10/50/3676882.jpg")
        val movie2: Movie = Movie("Jumanji","119 mn","Jake Kasdan","Adventure","2017","Quatre adolescents en détention découvrent une vieille console vidéo avec un jeu dont ils n'ont jamais entendu parler. Quand ils décident de jouer, ils sont immédiatement aspirés dans le monde jungle de Jumanji dans les corps de leurs avatars (Dwayne Johnson, Jack Black, Kevin Hart et Karen Gillan). Ils devront compléter l'aventure de leur vie remplie de plaisir, de sensations fortes et de danger ou être coincés dans le jeu pour toujours!","https://1645110239.rsc.cdn77.org/image/f330x470/q50/mm/befr/movies15872/posters/jumanji-bienvenue-dans-la-jungle.20181030033054.jpg")
        val movie3: Movie = Movie("Le seigneur des anneaux","178 mn","Peter Jackson","Adventure","2001","Le Seigneur des anneaux : La Communauté de l'anneau (The Lord of The Rings: The Fellowship of the Ring) est un film américano-néo-zélandais réalisé par Peter Jackson, sorti en 2001. C'est le premier volet de la trilogie Le Seigneur des anneaux et l'adaptation du livre La Fraternité de l'Anneau de J. R. R. Tolkien.","https://images-na.ssl-images-amazon.com/images/I/51YPE6TVDVL._SY445_.jpg")
        val movie4: Movie = Movie("Retour vers le futur","114 mn","Robert Zemeckis","Adventure","1985","Marty McFly est un adolescent américain des années 80: il va au lycée, aime le Rock, fait du skate-board... Mais son ami Emmett Brown, un physicien excentrique, va bouleverser sa vie quand celui-ci va lui demander de participer à une expérience de voyage dans le temps. Il se retrouve ainsi propulsé en 1955, à une époque où il n'était même pas né. Il va alors malencontreusement empêcher la rencontre amoureuse de ses parents quand ceux-ci n'étaient que des étudiants. Pour pouvoir exister, Marty va devoir jouer les entremetteurs avec ses géniteurs avant d'entamer son voyage de retour vers le futur.","http://fr.web.img2.acsta.net/medias/nmedia/18/35/91/26/18686482.jpg")
        val movie5: Movie = Movie("Indiana Jones","120 mn","Steven Spielberg","Adventure","1981","Pérou, 1936. Le professeur Henry Walton Jones Jr (dit « Indiana », ou « Indy »), éminent archéologue et expert en occultisme, est sur le point de mettre la main sur une idole Chachapoyan. Après avoir échappé à une série de pièges mortels dans un ancien temple, il se fait dérober la relique de façon déloyale par son principal concurrent, un archéologue français, René Belloq. Indy parvient à semer les indiens Hovito à bord d'un hydravion et rentre bredouille aux États-Unis.","")
        val movie6: Movie = Movie("Ghost Rider","114 mn","Mark Steven Johnson","Adventure","2007","À l'époque de la conquête de l'Ouest, le Diable, Méphistophélès (Peter Fonda), envoie son chasseur de primes, le Ghost Rider, pour signer son contrat avec un millier d'âmes corrompues de la ville de San Venganza. Puisque la nature du contrat pourrait donner à Méphistophélès la puissance nécessaire pour ramener l'enfer sur terre, le Rider refuse de lui donner ce contrat et part en cavale.","http://fr.web.img3.acsta.net/r_1280_720/pictures/16/02/11/13/42/165681.jpg")
        val movie7: Movie = Movie("Robin des Bois","140 mn","Ridley Scott","Adventure","2010","En 11991, l'archer Robin Longstride (Russell Crowe) déserte avec trois de ses compagnons l'armée anglaise après la mort du roi au siège de Châlus.","http://fr.web.img5.acsta.net/medias/nmedia/18/70/25/56/19409264.jpg")
        val movie8: Movie = Movie("La Momie","11 mn","Alex Kurtzman","Adventure","2017","Retrouvez Tom Cruise dans une aventure spectaculaire qui a fasciné de nombreuses générations à travers le monde : La Momie. Enterrée vivante, une princesse de l’ancienne Égypte qui a trahi sa lignée revient à la vie et va déverser sur notre monde des siècles de vengeance et de terreur. Des sables du Moyen-Orient aux pavés de Londres en passant par les ténébreux labyrinthes d’antiques tombeaux dérobés, La Momie nous transporte dans un monde envoûtant et terrifiant, peuplé de monstres et de divinités, revisitant ce mythe vieux comme le monde.","http://fr.web.img6.acsta.net/pictures/17/04/11/16/54/286958.jpg")
        val movie9: Movie = Movie("Inglorious Bastard","153 mn","Quentin Tarantino","Adventure","2009","Dans la France occupée de 1940, un groupe de soldats juifs américains, les bâtards, mène des actions punitives particulièrement sanglantes contre les nazis du Troisième Reich. Leur chemin rencontre celui de Shosanna Dreyfus, une jeune juive réfugiée à Paris exploitante d'une salle de cinéma qui entend elle aussi assouvir sa propre vengeance envers les nazis.","http://fr.web.img2.acsta.net/medias/nmedia/18/70/45/22/19123474.jpg")
        val movie10: Movie = Movie("Mortal Engine","221 mn","Christian Rivers","Adventure","2018","Des centaines d’années après qu’un évènement apocalyptique ait détruit la Terre, l’humanité s’est adaptée pour survivre en trouvant un nouveau mode de vie. Ainsi, de gigantesques villes mobiles errent sur Terre prenant sans pitié le pouvoir sur d’autres villes mobiles plus petites.","http://fr.web.img3.acsta.net/c_215_290/pictures/18/10/04/09/16/5370043.jpg")

        movies.add(movie1)
        movies.add(movie2)
        movies.add(movie3)
        movies.add(movie4)
        movies.add(movie5)
        movies.add(movie6)
        movies.add(movie7)
        movies.add(movie8)
        movies.add(movie9)
        movies.add(movie10)

        return movies
    }

    fun getRomanceMovies(): ArrayList<Movie> {
        val movies: ArrayList<Movie> = ArrayList()

        val movie1: Movie = Movie("Orgeil & Prejugé","127 mn","Joe Wright","Romance","2005","Orgueil et Préjugés (Pride & Prejudice) est une coproduction américano-franco-britannique réalisée par Joe Wright, sortie en 2005. Alors que cette œuvre majeure de la littérature anglaise a donné lieu à de très nombreuses adaptations télévisées depuis 1938, la dernière adaptation de la BBC datant de 1995, il ne s'agit que de la deuxième tentative de la porter sur grand écran, la première étant le film en noir et blanc de Robert Z. Leonard sorti en 1940, avec Greer Garson et Laurence Olivier.","http://fr.web.img6.acsta.net/medias/nmedia/18/35/99/80/18461215.jpg")
        val movie2: Movie = Movie("Coup de foudre à Nothing Hill","124 mn","Roger Michell","Romance","1999","Anna Scott est une des toutes grandes stars d'Hollywood qui brillent sur les écrans du monde entier. William Thacker est un jeune Anglais qui possède et dirige une librairie spécialisée dans les livres de voyage dans le charmant quartier de Notting Hill à Londres. Leur rencontre est improbable, pourtant..","http://fr.web.img6.acsta.net/pictures/187/980/18798040_20130813143310513.jpg")
        val movie3: Movie = Movie("Pretty Woman","116 mn","Garry Marshall","Romance","1990","PRETTY WOMAN : le face à face extraordinaire de deux monstres sacrés de Hollywood... D’un côté, Julia Roberts, de l’autre, le charismatique Richard Gere. Tel un conte de fées pour les grands, “Pretty Woman” raconte l’histoire d’une jeune femme de petite vertu - la superbe Julia Roberts - qui fait la rencontre de sa vie en la personne d’un business man très affairé, le très séduisant Richard Gere... Une histoire d’amour qui frise l’impossible. Humour, tendresse et quiproquos s’enchaînent dans un tourbillon endiablé plein de rebondissements que vient rythmer - entre autres - le célèbre morceau sur lequel a dansé plus d’une génération : “Pretty Woman”. PRETTY WOMAN, une comédie au charme aussi irrésistible que celui de ses héros, pour faire le plein de bonne humeur !","https://images-na.ssl-images-amazon.com/images/I/612oWOnZ5LL._SY679_.jpg")
        val movie4: Movie = Movie("Titanic","194 mn","James Cameron","Romance","1997","En septembre 1996, Brock Lovett est le coordinateur d'une équipe qui fouille méticuleusement l'épave du Titanic, paquebot géant réputé insubmersible qui connut pourtant un destin tragique. Lors d'une plongée en sous-marin miniature, il espère mettre enfin la main sur le Cœur de l'Océan, un bijou unique à la valeur inestimable, porté par Louis XVI, dont la découverte lui apporterait la gloire (ce bijou est inspiré du diamant bleu de la Couronne). Mais il remonte des profondeurs un coffre-fort qui se révèle ne contenir qu'un dessin représentant une jeune fille nue portant le bijou en pendentif.","https://1645110239.rsc.cdn77.org/image/f330x470/q50/mm/befr/movies10599/posters/titanic-3d.20170228031349.jpg")
        val movie5: Movie = Movie("Forrest Gump","142 mn","Robert Zemeckis","Romance","1994","«La vie, c’est comme une boîte de chocolats…On ne sait jamais sur quoi on va tomber.» Tom Hanks est merveilleux dans ce film culte qui a touché le coeur de milliers de spectateurs. Forrest Gump est le symbole d’une époque, un candide dans une Amérique qui a perdu son innocence. Ce film a remporté 6 Oscars® dont celui du meilleur film, du meilleur réalisateur (Robert Zemeckis) et du meilleur acteur (Tom Hanks).","https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Forrest_Gump_poster.jpg/220px-Forrest_Gump_poster.jpg")
        val movie6: Movie = Movie("Avant Toi","110 mn","Thea Sharrock","Romance","2016","Louisa Clark, dite Lou, (Emilia Clarke) est une jeune fille excentrique qui multiplie les petits boulots pour aider sa famille à joindre les deux bouts. Sa bonne humeur est mise à rude épreuve quand elle devient l'aide-soignante de Will Traynor (Sam Claflin), un jeune et riche banquier paralysé dans un accident deux ans plus tôt. Peu à peu, avec l'aide de Louisa, Will perd son cynisme et reprend goût à la vie. À mesure que leur amitié grandit, leurs sentiments évoluent et leurs vies prennent un tour qu'ils n'auraient jamais imaginé.","https://is3-ssl.mzstatic.com/image/thumb/Video30/v4/7d/34/af/7d34afd1-7d07-4f8b-3de9-69f86e336d85/pr_source.lsr/268x0w.png")
        val movie7: Movie = Movie("Jeu d'enfants","93 mn","Yann Samuell","Romance","2003","Julien, 8 ans, est confronté au cancer de sa mère, tandis que Sophie doit affronter la xénophobie des autres écoliers. Très vite ils deviennent inséparables et s'inventent un jeu : « cap ou pas cap ? » (capable ou pas capable ?). C'est à celui qui, mis au défi par l'autre, fera les pires bêtises, au grand désespoir des adultes.","http://fr.web.img4.acsta.net/c_215_290/medias/nmedia/18/35/10/90/affiche2.jpg")
        val movie8: Movie = Movie("Cher John","105 mn","Lasse Hallström","Romance","2010","Cher John (Dear John) est un film romantique américain de Lasse Hallström, sorti en 2010. Réalisé par Lasse Hallström, le film est une adaptation du roman Cher John de Nicholas Sparks. Il montre la vie d'un soldat qui tombe amoureux d'une jeune femme lors d'une permission. Lorsqu'il doit retourner en mission, ils décident alors de s'échanger des lettres. Amanda Seyfried, l'actrice principale, a enregistré une chanson pour le film intitulée Little House.","http://fr.web.img3.acsta.net/medias/nmedia/18/72/91/60/19262319.jpg")
        val movie9: Movie = Movie("Ps I Love You","126 mn","Richard LaGravenese","Romance","2007","Holly et Gerry sont un couple marié, qui vit dans le Lower East Side, à Manhattan. Lorsque celui-ci meurt subitement d'une tumeur cérébrale, Holly s'éloigne de sa famille et de ses amis et sombre dans une profonde dépression. Jusqu'au jour où elle reçoit pour son trentième anniversaire un gâteau et un enregistrement audio avec la voix de son mari. Sur ces enregistrements, Gerry la pousse à reprendre le contrôle de sa vie et à sortir de son état psychologique. D'autres messages suivront, dans lesquels il amène Holly à suivre ses directives au travers de dix lettres se terminant toutes par : « P.S. I Love You ». Cette quête l'amènera à partir en Irlande, terre d'origine de Gerry, où ils se sont rencontrés pour la première fois.","http://fr.web.img5.acsta.net/r_1280_720/pictures/15/11/12/08/41/394310.jpg")
        val movie10: Movie = Movie("Oublie Jamais","123 mn","Nick Cassavetes","Romance","2004","Atteinte de la maladie d'Alzheimer, Allie a tout oublié de sa vie. Chaque jour, Duke vient lui lire le récit de deux jeunes gens qui se sont passionnément aimés dans les années 40, avant que l'existence et les conventions ne les séparent. Si elle ne peut plus se souvenir, Allie peut encore ressentir, et la voix de Duke fait ressurgir le passé et une magnifique histoire d'amour. Ces mots, Allie les connaît, elle a parfois l'impression de les avoir déjà lus, de les avoir peut-être écrits...","http://fr.web.img3.acsta.net/medias/nmedia/18/35/32/48/18384546.jpg")

        movies.add(movie1)
        movies.add(movie2)
        movies.add(movie3)
        movies.add(movie4)
        movies.add(movie5)
        movies.add(movie6)
        movies.add(movie7)
        movies.add(movie8)
        movies.add(movie9)
        movies.add(movie10)

        return movies
    }

    fun getHorrorMovies(): ArrayList<Movie> {
        val movies: ArrayList<Movie> = ArrayList()

        val movie1: Movie = Movie("Vendredi 13","97 mn","Marcus Nispel","Horreur","1980","Juin 1980, la nuit du Vendredi 13, Jason Voorhees, un petit garçon difforme, assiste à la décapitation de sa mère psychopathe, Pamela Voorhees. Donné pour mort, il déambule dans la région abandonnée de Crystal Lake. Au fil des années, il acquiert une force surhumaine et une rage aveugle envers tous les adultes. Aujourd’hui, 20 ans plus tard, un groupe d’adolescents décide de passer un week-end près du lac de Crystal Lake, et vont déclencher la folie meurtrière de Jason. Par la suite, le frère d'une victime va enquêter pour retrouver la trace de sa sœur disparue...","https://m.media-amazon.com/images/M/MV5BMTQ5ODI5NTMzN15BMl5BanBnXkFtZTcwNzY4MTYxMg@@._V1_.jpg")
        val movie2: Movie = Movie("Carrie","100 mn","Kimberly Peirce","Horreur","2013","Timide et surprotégée par sa mère très pieuse, Carrie est une lycéenne rejetée par ses camarades. Le soir du bal de fin d'année, elle subit une sale blague de trop. Carrie déchaîne alors de terrifiants pouvoirs surnaturels auxquels personne n'échappera.","http://t0.gstatic.com/images?q=tbn:ANd9GcSpELLWo_Kyn8LQDMYfgHK-AN4rkDj-noiICGP2XGtcw6qjpzXC")
        val movie3: Movie = Movie("Insidious","102 mn","James Wan","Horreur","2010","Josh, son épouse et leurs trois enfants vivent depuis peu dans leur nouvelle maison lorsque l’aîné tombe dans un coma inexpliqué. Étrangement, une succession de phénomènes paranormaux débute peu après. Un médium leur révèle alors que l’âme de leur fils se trouve quelque part entre la vie et la mort, dans la dimension astrale, et que les manifestations sont l’oeuvre de forces maléfiques voulant s’emparer de son enveloppe corporelle. Pour le sauver, Josh va devoir lui aussi quitter son corps et s’aventurer dans l’au-delà ..","https://upload.wikimedia.org/wikipedia/en/2/2d/Insidious_poster.jpg")
        val movie4: Movie = Movie("Annabelle","98 mn","John R. Leonetti","Horreur","2014","John Form est certain d'avoir déniché le cadeau de ses rêves pour sa femme Mia, qui attend un enfant. Il s'agit d'une poupée ancienne, très rare, habillée dans une robe de mariée d'un blanc immaculé. Mais Mia, d'abord ravie par son cadeau, va vite déchanter.Une nuit, les membres d'une secte satanique s'introduisent dans leur maison et agressent sauvagement le couple, paniqué. Et ils ne se contentent pas de faire couler le sang et de semer la terreur – ils donnent vie à une créature monstrueuse, pire encore que leurs sinistres méfaits, permettant aux âmes damnées de revenir sur Terre : Annabelle…","https://www.google.fr/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwi62ZDP_PLeAhXFGuwKHQqIDkwQjRx6BAgBEAU&url=http%3A%2F%2Fwww.allocine.fr%2Ffilm%2Ffichefilm-225218%2Fphotos%2Fdetail%2F%3Fcmediafile%3D21138276&psig=AOvVaw1Gsn73HXmZNYCmF4CZB1Ll&ust=1543353138954135")
        val movie5: Movie = Movie("Ouija","89 mn","Stiles White","Horreur","2014","Un groupe d'amis doivent affronter leurs peurs les plus terrifiantes lorsqu'ils réveillent les sombres pouvoirs d'un ancien plateau de spiritisme..","http://fr.web.img4.acsta.net/r_1280_720/pictures/14/11/06/10/22/155002.jpg")
        val movie6: Movie = Movie("Paranormal Activity","86 mn","Oren Peli","Horreur","2009","Un jeune couple s'installe dans une maison en banlieue. Le bonheur fait place à la terreur lorsqu'ils doivent repousser, toutes les nuits, les attaques d'un esprit démoniaque...","https://www.google.fr/url?sa=i&source=imgres&cd=&cad=rja&uact=8&ved=2ahUKEwillcDd_fLeAhXIsaQKHW2ZC04QjRx6BAgBEAU&url=http%3A%2F%2Fwww.allocine.fr%2Ffilm%2Ffichefilm_gen_cfilm%3D140608.html&psig=AOvVaw31_pbHtPrcW38_5dffoz_8&ust=1543353439307278")
        val movie7: Movie = Movie("Hostel","94 mn","Eli Roth","Horreur","2006","Deux étudiants américains, Paxton et Josh, ont décidé de découvrir l'Europe avec un maximum d'aventures et de sensations fortes.","https://www.google.fr/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjfh-Of__LeAhUECewKHSvoBTwQjRx6BAgBEAU&url=http%3A%2F%2Fwww.allocine.fr%2Ffilm%2Ffichefilm-108925%2Fphotos%2Fdetail%2F%3Fcmediafile%3D18470658&psig=AOvVaw3hDaECBZRq3tLfSapUgr8j&ust=1543353845561162")
        val movie8: Movie = Movie("Conjuring","110 mn","James Wan","Horreur","2013","Avant Amityville, il y avait Harrisville… Conjuring : Les dossiers Warren, raconte l'histoire horrible, mais vraie, d'Ed et Lorraine Warren, enquêteurs paranormaux réputés dans le monde entier, venus en aide à une famille terrorisée par une présence inquiétante dans leur ferme isolée… Contraints d'affronter une créature démoniaque d'une force redoutable, les Warren se retrouvent face à l'affaire la plus terrifiante de leur carrière…","https://www.google.fr/url?sa=i&source=imgres&cd=&cad=rja&uact=8&ved=2ahUKEwi26b7n_vLeAhXD6aQKHbFiDWkQjRx6BAgBEAU&url=http%3A%2F%2Ft0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcT6geB1X38928Kh0m2KNvXEj_fnPyvGmlVXILqg2kyhdrN0MFyo&psig=AOvVaw0ekLAFtuw6JLOZG29Nc0i9&ust=1543353728686655")
        val movie9: Movie = Movie("Shinning","146 mn","Stanley Kubrick","Horreur","1980","Jack Torrance, gardien d'un hôtel fermé l'hiver, sa femme et son fils Danny s'apprêtent à vivre de longs mois de solitude. Danny, qui possède un don de médium, le Shining, est effrayé à l'idée d'habiter ce lieu, théâtre marqué par de terribles évènements passés..","https://www.google.fr/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjlrbGH__LeAhUFyqQKHagZCZYQjRx6BAgBEAU&url=https%3A%2F%2Fwww.kurosawa-cinema.com%2Fthe-shinning%2F&psig=AOvVaw0TFIQoG9MCAzXGgZEIGwg8&ust=1543353794356928")
        val movie10: Movie = Movie("Exorciste","122 mn","William Friedkin","Horreur","1974","Regan, âgée de 12 ans, souffre d'inquiétants troubles du comportement. Après de nombreux examens médicaux, sa mère Chris MacNeil sollicite l'aide d'un jeune prête psychiatre, le Père Karras qui lui apprend que la jeune fille est possédée par le diable. Avec l'aide de son confrère le père Merrin, il va se lancer dans des séances d'exorcisme d'une incroyable intensité","http://fr.web.img5.acsta.net/medias/nmedia/18/65/19/82/18835952.jpg")

        movies.add(movie1)
        movies.add(movie2)
        movies.add(movie3)
        movies.add(movie4)
        movies.add(movie5)
        movies.add(movie6)
        movies.add(movie7)
        movies.add(movie8)
        movies.add(movie9)
        movies.add(movie10)

        return movies
    }

    fun getSFMovies(): ArrayList<Movie> {
        val movies: ArrayList<Movie> = ArrayList()

        val movie1: Movie = Movie("Harry Potter à l'école des soricers","152 mn","Chris Columbus","SF","2001","Orphelin, le jeune Harry Potter peut enfin quitter ses tyranniques oncle et tante Dursley lorsqu'un curieux messager lui révèle qu'il est un sorcier. À 11 ans, Harry va enfin pouvoir intégrer la légendaire école de sorcellerie de Poudlard, y trouver une famille digne de ce nom et des amis, développer ses dons, et préparer son glorieux avenir.","http://fr.web.img2.acsta.net/pictures/18/07/02/17/25/3643090.jpg")
        val movie2: Movie = Movie("Les animaux fantastique","133 mn","David Yates","SF","2016","Norbert Dragonneau rentre à peine d'un périple à travers le monde où il a répertorié un bestiaire extraordinaire de créatures fantastiques. Il pense faire une courte halte à New York, mais une série d'événements et de rencontres inattendues risquent de prolonger son séjour. Désormais, le monde de la magie est menacé.","http://fr.web.img3.acsta.net/pictures/16/10/11/09/32/205295.jpg")
        //val movie3: Movie = Movie("Twilight, chapitre I : Fascination","130 mn","Catherine Hardwicke","SF","2009","Isabella Swan, 17 ans, déménage à Forks, petite ville pluvieuse dans l'Etat de Washington, pour vivre avec son père. Au lycée, elle est terriblement intriguée par le comportement d'une étrange fratrie, deux filles et trois garçons. Bella tombe follement amoureuse de l'un d'eux, Edward Cullen. Une relation sensuelle et dangereuse commence alors entre les deux jeunes gens : lorsque Isabella comprend que Edward est un vampire, il est déjà trop tard.","")
        val movie4: Movie = Movie("Pirates des Caraïbes : La Malédiction du Black Pearl","142 mn","Gore Verbinski","SF","2003","Petite, Elizabeth Swann, la fille du gouverneur, a sauvé de la noyade Will Turner après le naufrage de son bateau. Les années ont passé, Will et Elizabeth ont grandi. Will est devenu forgeron à Port Royal, et Elizabeth se prépare à épouser le commodore Norrington. Cependant, la vie d'Elizabeth bascule lorsque le capitaine Barbossa et sa bande de pirates décident d'attaquer Port Royal et la prennent en otage. Malheureusement pour lui, Barbossa a commis deux erreurs.","http://fr.web.img4.acsta.net/medias/nmedia/18/35/07/46/affiche2.jpg")
        val movie5: Movie = Movie("Avatar","178 mn","James Cameron","SF","2009","Malgré sa paralysie, Jake Sully, un ancien marine immobilisé dans un fauteuil roulant, est resté un combattant au plus profond de son être. Il est recruté pour se rendre à des années-lumière de la Terre, sur Pandora, où de puissants groupes industriels exploitent un minerai rarissime destiné à résoudre la crise énergétique sur Terre.","http://t3.gstatic.com/images?q=tbn:ANd9GcTA4nJB9z9llRSjgDa4SrU-Jwtb-3dwzkt90rF7KkCka1H90HDt")
        val movie6: Movie = Movie("Star Wars","136 mn","George Lucas","SF","1999","Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l'âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel. Pendant ce temps, l'armée de droïdes de l'insatiable Fédération du Commerce a envahi Naboo dans le cadre d'un plan secret des Sith visant à accroître leur pouvoir.","https://images-na.ssl-images-amazon.com/images/I/A1kk7kfbYHL._SY355_.jpg")
        val movie8: Movie = Movie("Interstellar","169 mn","Christopher Nolan","SF","2014","Dans un futur proche, la Terre est de moins en moins accueillante pour l'humanité qui connaît une grave crise alimentaire. Le film raconte les aventures d'un groupe d'explorateurs qui utilise une faille récemment découverte dans l'espace-temps afin de repousser les limites humaines et partir à la conquête des distances astronomiques dans un voyage interstellaire.","http://t1.gstatic.com/images?q=tbn:ANd9GcSIVryzUKVaqs-5yb0-uHykg7Ob4rUWFl-Ojl28OvBExh8Xc8GT")
        val movie9: Movie = Movie("Blade Runner 2049","164 mn","Denis Villeneuve","SF","2017","En 2049, la société est fragilisée par les nombreuses tensions entre les humains et leurs esclaves créés par bioingénierie. L'officier K est un Blade Runner : il fait partie d'une force d'intervention d'élite chargée de trouver et d'éliminer ceux qui n'obéissent pas aux ordres des humains. Lorsqu'il découvre un secret enfoui depuis longtemps et capable de changer le monde, les plus hautes instances décident que c'est à son tour d'être traqué et éliminé.","http://t0.gstatic.com/images?q=tbn:ANd9GcR4T2DSZLl0J7Oz7UdQjxpK7oKqe-sdnSJZ3UgL6WVhW9fslQ8s")
        val movie10: Movie = Movie("Alien","117","Ridley Scott","SF","1979","Durant le voyage de retour d'un immense cargo spatial en mission commerciale de routine, ses passagers, cinq hommes et deux femmes plongés en hibernation, sont tirés de leur léthargie dix mois plus tôt que prévu par Mother, l'ordinateur de bord. Ce dernier a en effet capté dans le silence interplanétaire des signaux sonores, et suivant une certaine clause du contrat de navigation, les astronautes sont chargés de prospecter tout indice de vie dans l'espace.","http://fr.web.img3.acsta.net/medias/nmedia/18/35/14/60/18363837.jpg")

        movies.add(movie1)
        movies.add(movie2)
        //movies.add(movie3)
        movies.add(movie4)
        movies.add(movie5)
        movies.add(movie6)
        movies.add(movie8)
        movies.add(movie9)
        movies.add(movie10)

        return movies
    }

}